# Generated by Django 4.1.3 on 2023-02-01 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iotapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='user',
        ),
        migrations.DeleteModel(
            name='DailySensorData',
        ),
        migrations.DeleteModel(
            name='SensorData',
        ),
    ]
