# Generated by Django 4.1.3 on 2023-02-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotapp', '0003_sensordata_dailysensordata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarkari', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
            ],
        ),
    ]
